Repository CleoMenezesJr/escambo, pull requests merged in 2023-05, with the labels that each got.

#29 :truck: Rename project's name
  .github/workflows/build_flatpak.yml
  README.md
  data/icons/hicolor/scalable/apps/io.github.cleomenezesjr.Escambo.Devel.svg
  data/icons/hicolor/scalable/apps/io.github.cleomenezesjr.Escambo.svg
  data/icons/hicolor/symbolic/apps/io.github.cleomenezesjr.Escambo-symbolic.svg
  data/icons/io.github.cleomenezesjr.Escambo.Source.svg
  data/icons/meson.build
  data/io.github.cleomenezesjr.Escambo.appdata.xml.in
  data/io.github.cleomenezesjr.Escambo.desktop.in
  data/io.github.cleomenezesjr.Escambo.gschema.xml
  data/meson.build
  io.github.cleomenezesjr.Escambo.json
  meson.build
  po/POTFILES
  po/meson.build
  po/pt_BR.po
  src/date_row.py
  src/dialog_cookies.py
  src/dialog_headers.py
  src/escambo.gresource.xml
  src/escambo.in
  src/gtk/window.blp
  src/main.py
  src/meson.build
  src/populator_entry.py
  src/restapi.py
  src/window.py
Labels: enhancement

#48 :fire: Remove "Authentication" and use "Authorization" instead
  data/io.github.cleomenezesjr.Escambo.gschema.xml
  po/de.po
  po/pt_BR.po
  src/restapi.py
  src/window.py
Labels: enhancement

#50 :beetle: Fix miswrite label
  src/gtk/window.blp
Labels: bug

#51 :tada: Add duplicate check to form data's keys
  src/window.py
Labels: enhancement

#55 :beetle: Fix headers related bugs
  src/dialog_headers.py
  src/window.py
Labels: bug, enhancement

#49 :recycle: Use syntax introduced in blueprint 0.8.0
  src/gtk/date-row.blp
  src/gtk/dialog-body.blp
  src/gtk/dialog-cookies.blp
  src/gtk/dialog-headers.blp
  src/gtk/populator-entry.blp
  src/gtk/window.blp
Labels: enhancement

#60 :lipstick: Make headerbars flat where appropriate
  src/gtk/window.blp
Labels: enhancement

#64 :sparkles: Reformat all blueprint files
  src/gtk/date-row.blp
  src/gtk/dialog-body.blp
  src/gtk/dialog-cookies.blp
  src/gtk/dialog-headers.blp
  src/gtk/populator-entry.blp
  src/gtk/window.blp
Labels: enhancement
